<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>
  
</body>
<script>
  /*
   Promise
    是一个构造函数  接受一个参数：callback 我们把要执行的异步任务放在这个callback 函数中
    Promise 内部会维护一个状态
      默认是pending
      成功: resolved
      失败: rejected

    Promise对象下有一个方法：then 该方法在Promise对象的状态发生改变的时候触发then的回调

  */ 
  let p1 = new Promise((resolve, reject) => {
    // 当Promise被实例化的时候，callback 的异步任务就会被执行
    // 我们可以通过传入resolved 和 rejected , 去改变当前 Promise 任务的状态
    // 调用 resolve 会把状态变成 resolved 调用 reject 会变成 rejected
    setTimeout(() => {
      console.log(1);
      //resolve();
      reject()
    }, 500)
  })
  //console.log(p1);
  // then 会接受俩个参数：这俩个参数都是回调函数，当对应的promise对象的状态变成了resolved,
  //那么then的第一个callback就会被执行，如果状态变成了rejected,那么then的第二个callback就会被执行
  // let p2 = p1.then(() => { // p1.then执行完毕后会继续返回一个Promise对象，p2不等于p1，但是p2会继承第一个promise对象的状态
  //   console.log('success');

  // }, () => {
  //   console.log('failed');

  // })

 // 这里有个细节要注意，p1.then 返回的promise对象默认都是成功的promise如果想接下来走失败的回调，要手动返回一个失败的promise
  p1.then(() => {
    console.log(1);
  }, () => {
    // 下面这段代码可以简写成 return Promise.reject()
    return new Promise((resolve, reject) => {
      reject();
    })
  }).then(() => {
    console.log(2);
  }).then(() => {
    console.log(3); 
  }).catch(err => { //catch 和then 一样，也会返回一个默认resolved状态的promise对象
    console.log('cuole');
  }).then(() => {
    console.log(4);
  })
  
</script>
</html>